version: '2'

services:

    sbrest-servise:
      image: adambemben/sbrestservice4jaeger:1.1
      ports:
        - "8083:8083"


    sbrest-client:
      image: adambemben/sbrestclient4jaeger:1.1
      ports:
        - "8087:8087"
      depends_on:
        - sbrest-servise