version: '2'

services:
    
    jaeger-agent:
      image: jaegertracing/jaeger-agent:1.17.1
      command: ["--reporter.grpc.host-port=jaeger-collector:14250"]
      ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
      restart: on-failure
    
    jaxrs-server:
      image: rafalcurylo/jaxserver4jaeger:1.6
      ports:
        - "8081:8080"
      
    jaxrs-client:
      image: rafalcurylo/jaxclient4jaeger:1.6
      ports:
        - "8080:8080"
      