version: '3.7'

services:
   
    jaeger-agent:
      image: jaegertracing/jaeger-agent:1.17.1
      command: ["--reporter.grpc.host-port=jaeger-collector:14250"]
      ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
      restart: on-failure
      
      
    sbrest-servise:
      image: adambemben/sbrestservice4jaeger:1.6
      ports:
        - "9083:9083"


    sbrest-client:
      image: adambemben/sbrestclient4jaeger:1.6
      ports:
        - "9087:9087"
      depends_on:
        - sbrest-servise