version: '3.7'

services:

    cassandra:
      image: cassandra:3.9
      networks:
        - jaeger-net

    cassandra-schema:
      image: jaegertracing/jaeger-cassandra-schema:1.17.1
      networks:
        - jaeger-net
      depends_on:
        - cassandra
    
    jaeger-collector:
      container_name: collector
      image: jaegertracing/jaeger-collector:1.17.1
      command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra", "--collector.zipkin.http-port=9411"]
      ports:
        - "14269"
        - "14268:14268"
        - "14250"
        - "9411:9411"
      networks:
        - jaeger-net        
      restart: on-failure
      depends_on:
        - cassandra-schema

    jaeger-query:
      image: jaegertracing/jaeger-query:1.17.1
      command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra"]
      ports:
        - "16686:16686"
        - "16687"
      networks:
        - jaeger-net        
      restart: on-failure
      depends_on:
        - cassandra-schema

networks: 
  jaeger-net:
    driver: bridge
    name: jeager-net